<?php 

/**
 * Implementation of hook_token_values()
 * 
 * @param string $type
 * @param object $object
 * @param array $options
 *
 * @return array
 */
function reload_tokens_token_values($type, $object = NULL, $options = array()){
	if($type=='node'){
		
    $mlid = db_result(db_query("SELECT mlid FROM {menu_links} WHERE link_path = '%s'", 'node/'. $object->nid));
		
    if (!empty($mlid) || !empty($node->menu['mlid']) || !empty($node->menu['plid'])) {
      $menu_link = menu_link_load($mlid);
      $menus = menu_get_menus();
      $menu = isset($menus[$menu_link['menu_name']]) ? $menus[$menu_link['menu_name']] : '';
      $trail_raw = _menu_titles($menu_link, $node->nid);

      $path = implode('/', $trail_raw);
    }
    // The actual fallback feature 
		if(!$path){
		  $path = $object->title;
		}
		//$tokens['menupath_with_fallback_to_title'] = $path;
    $tokens['menupath_with_fallback_to_title-path-raw'] = $path;
    return $tokens;	
	}
}

/**
 * Implementation of hook_token_list()
 * 
 * @param string $type
 * 
 * *return array
 */
function reload_tokens_token_list($type = 'all'){
 $tokens = array();
  if ($type == 'node') {
  	//$tokens['node']['menupath_with_fallback_to_title-path'] = t('Use title if no menupath is present');
    $tokens['node']['menupath_with_fallback_to_title-path-raw'] = t('Use title if no menupath is present');
  }
	return $tokens;
}